# Generated by Django 3.1.7 on 2022-09-18 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 9, 21, 52, 910445), null=True),
        ),
    ]
